### ISSUE TITLE
Not working in new domain!

### ISSUE THREAD

**Issue by martin9700** [martin9700/Get-SAUser#1]
Works great in the domain it was developed on, but completely blew chunks in another.  Looks like the initial ADSI calls might be failing.

**Comment by KidSunday** [comment]
Martin - For what it's worth - I was able to get the ADSI Search portion working on my test domain.
I did run into a Null array error on line 130 with several test users.
This seems to be occurring if ANY of the properties/fields are blank.  In my case it was Description and Manager.  Once I entered dummy information, everything worked.  
Hope that helps!

**Comment by martin9700** [comment]
Hi Drew, that makes a lot of sense.  Going to be reworking some things!

**Comment by martin9700** [comment]
@KidSunday Hey Drew, put in a bug fix that I think will solve the problem you had.  You'll need to switch to the dev branch to get the latest update. Assuming that works I'll commit it to the master branch.

**Comment by martin9700** [comment]
@KidSunday Drew, have you had a chance to test the new version from the dev branch?

**Comment by KidSunday** [comment]
I did!  Its working great in my dev domain environment.
